function compile(fcnStr)

if nargin == 0
	fcnStr = 'all';
end

libDir     = '/usr/local/cuda/lib64';
includeDir = 'include';
matlabFlag = '-R2018a';

% - - -

if strcmpi(fcnStr, '2D_frame_objfcn') || strcmpi(fcnStr, '2D_frame') || strcmpi(fcnStr, 'all')

	files = ...
	{
	'2D_frame/computeObjfcn.cu', ...
	'2D_frame/assignStructMemory.cu', ...
	'2D_frame/objfcn.cu', ...
	'2D_frame/tauInitialITF.cu', ...
	'2D_frame/tauInitial.cu', ...
	'2D_frame/vertexToEdge.cu', ...
	'2D_frame/vertexToBottom.cu', ...
	'2D_frame/computeFrameITF.cu', ...
	'2D_frame/computeFrame.cu', ...
	'2D_frame/assembleFemMatrixITF.cu', ...
	'2D_frame/assembleFemMatrix.cu', ...
	'2D_frame/yankTauActivityITF.cu', ...
	'2D_frame/yankTauActivity.cu', ...
	'2D_frame/reactionTauActivityITF.cu', ...
	'2D_frame/reactionTauActivity.cu', ...
	'2D_frame/computeKernelITF.cu', ...
	'2D_frame/computeKernel.cu', ...
	'2D_frame/addEpsIdentity.cu', ...
	'2D_frame/cholesky.cu', ...
	'2D_frame/computeExternalYankITF.cu', ...
	'2D_frame/computeExternalYank.cu', ...
	'2D_frame/ipcg.cu', ...
	'2D_frame/ipcgWholeMatrixMultiplication.cu', ...
	'2D_frame/ipcgSecondMatrixMultiplication.cu', ...
	'2D_frame/ipcgKernelMultiplication.cu', ...
	'2D_frame/computeStrainTensor.cu', ...
	'2D_frame/applyFrameElasticOperatorITF.cu', ...
	'2D_frame/applyFrameElasticOperator.cu', ...
	'2D_frame/applyPenaltyOperatorITF.cu', ...
	'2D_frame/applyPenaltyOperator.cu', ...
	'2D_frame/assembleFemVectorITF.cu', ...
	'2D_frame/assembleFemVector.cu', ...
	'2D_frame/varifoldITF.cu', ...
	'2D_frame/varifold.cu', ...
	'2D_frame/dsum.cu', ...
	'2D_frame/vectoraxpby.cu', ...
	};
	
	fprintf('Compiling computeObjfcn (2D_frame)...\n');
	mexcuda(matlabFlag, '-DDIM2', ['-L', libDir], ['-I', includeDir], files, ...
	        '-lcublas', '-lcusolver', '-output', 'computeObjfcn_2D_frame');
	fprintf('\n');

end
	
if strcmpi(fcnStr, '2D_frame_deform') || strcmpi(fcnStr, '2D_frame') || strcmpi(fcnStr, 'all')

	files = ...
	{
	'2D_frame/deformation.cu', ...
	'2D_frame/assignStructMemory.cu', ...
	'2D_frame/deform.cu', ...
	'2D_frame/tauInitialITF.cu', ...
	'2D_frame/tauInitial.cu', ...
	'2D_frame/vertexToEdge.cu', ...
	'2D_frame/vertexToBottom.cu', ...
	'2D_frame/computeFrameITF.cu', ...
	'2D_frame/computeFrame.cu', ...
	'2D_frame/assembleFemMatrixITF.cu', ...
	'2D_frame/assembleFemMatrix.cu', ...
	'2D_frame/yankTauActivityITF.cu', ...
	'2D_frame/yankTauActivity.cu', ...
	'2D_frame/reactionTauActivityITF.cu', ...
	'2D_frame/reactionTauActivity.cu', ...
	'2D_frame/computeKernelITF.cu', ...
	'2D_frame/computeKernel.cu', ...
	'2D_frame/addEpsIdentity.cu', ...
	'2D_frame/cholesky.cu', ...
	'2D_frame/computeExternalYankITF.cu', ...
	'2D_frame/computeExternalYank.cu', ...
	'2D_frame/ipcg.cu', ...
	'2D_frame/ipcgWholeMatrixMultiplication.cu', ...
	'2D_frame/ipcgSecondMatrixMultiplication.cu', ...
	'2D_frame/ipcgKernelMultiplication.cu', ...
	'2D_frame/computeStrainTensor.cu', ...
	'2D_frame/applyFrameElasticOperatorITF.cu', ...
	'2D_frame/applyFrameElasticOperator.cu', ...
	'2D_frame/applyPenaltyOperatorITF.cu', ...
	'2D_frame/applyPenaltyOperator.cu', ...
	'2D_frame/assembleFemVectorITF.cu', ...
	'2D_frame/assembleFemVector.cu', ...
	'2D_frame/varifoldITF.cu', ...
	'2D_frame/varifold.cu', ...
	'2D_frame/dsum.cu', ...
	'2D_frame/vectoraxpby.cu', ...
	};
	
	fprintf('Compiling deformation (2D_frame)...\n');
	mexcuda(matlabFlag, '-DDIM2', ['-L', libDir], ['-I', includeDir], files, ...
	        '-lcublas', '-lcusolver', '-output', 'deformation_2D_frame');
	fprintf('\n');

end

% - - -

if strcmpi(fcnStr, '3D_frame_objfcn') || strcmpi(fcnStr, '3D_frame') || strcmpi(fcnStr, 'all')

	files = ...
	{
	'3D_frame/computeObjfcn.cu', ...
	'3D_frame/assignStructMemory.cu', ...
	'3D_frame/objfcn.cu', ...
	'3D_frame/tauInitialITF.cu', ...
	'3D_frame/tauInitial.cu', ...
	'3D_frame/vertexToEdge.cu', ...
	'3D_frame/vertexToBottom.cu', ...
	'3D_frame/computeFrameITF.cu', ...
	'3D_frame/computeFrame.cu', ...
	'3D_frame/assembleFemMatrixITF.cu', ...
	'3D_frame/assembleFemMatrix.cu', ...
	'3D_frame/yankTauActivityITF.cu', ...
	'3D_frame/yankTauActivity.cu', ...
	'3D_frame/reactionTauActivityITF.cu', ...
	'3D_frame/reactionTauActivity.cu', ...
	'3D_frame/computeKernelITF.cu', ...
	'3D_frame/computeKernel.cu', ...
	'3D_frame/addEpsIdentity.cu', ...
	'3D_frame/cholesky.cu', ...
	'3D_frame/computeExternalYankITF.cu', ...
	'3D_frame/computeExternalYank.cu', ...
	'3D_frame/ipcg.cu', ...
	'3D_frame/ipcgWholeMatrixMultiplication.cu', ...
	'3D_frame/ipcgSecondMatrixMultiplication.cu', ...
	'3D_frame/ipcgKernelMultiplication.cu', ...
	'3D_frame/computeStrainTensor.cu', ...
	'3D_frame/applyFrameElasticOperatorITF.cu', ...
	'3D_frame/applyFrameElasticOperator.cu', ...
	'3D_frame/applyPenaltyOperatorITF.cu', ...
	'3D_frame/applyPenaltyOperator.cu', ...
	'3D_frame/assembleFemVectorITF.cu', ...
	'3D_frame/assembleFemVector.cu', ...
	'3D_frame/varifoldITF.cu', ...
	'3D_frame/varifold.cu', ...
	'3D_frame/dsum.cu', ...
	'3D_frame/vectoraxpby.cu', ...
	};
	
	fprintf('Compiling computeObjfcn (3D_frame)...\n');
	mexcuda(matlabFlag, '-DDIM3', ['-L', libDir], ['-I', includeDir], files, ...
	        '-lcublas', '-lcusolver', '-output', 'computeObjfcn_3D_frame');
	fprintf('\n');

end
	
if strcmpi(fcnStr, '3D_frame_deform') || strcmpi(fcnStr, '3D_frame') || strcmpi(fcnStr, 'all')

	files = ...
	{
	'3D_frame/deformation.cu', ...
	'3D_frame/assignStructMemory.cu', ...
	'3D_frame/deform.cu', ...
	'3D_frame/tauInitialITF.cu', ...
	'3D_frame/tauInitial.cu', ...
	'3D_frame/vertexToEdge.cu', ...
	'3D_frame/vertexToBottom.cu', ...
	'3D_frame/computeFrameITF.cu', ...
	'3D_frame/computeFrame.cu', ...
	'3D_frame/assembleFemMatrixITF.cu', ...
	'3D_frame/assembleFemMatrix.cu', ...
	'3D_frame/yankTauActivityITF.cu', ...
	'3D_frame/yankTauActivity.cu', ...
	'3D_frame/reactionTauActivityITF.cu', ...
	'3D_frame/reactionTauActivity.cu', ...
	'3D_frame/computeKernelITF.cu', ...
	'3D_frame/computeKernel.cu', ...
	'3D_frame/addEpsIdentity.cu', ...
	'3D_frame/cholesky.cu', ...
	'3D_frame/computeExternalYankITF.cu', ...
	'3D_frame/computeExternalYank.cu', ...
	'3D_frame/ipcg.cu', ...
	'3D_frame/ipcgWholeMatrixMultiplication.cu', ...
	'3D_frame/ipcgSecondMatrixMultiplication.cu', ...
	'3D_frame/ipcgKernelMultiplication.cu', ...
	'3D_frame/computeStrainTensor.cu', ...
	'3D_frame/applyFrameElasticOperatorITF.cu', ...
	'3D_frame/applyFrameElasticOperator.cu', ...
	'3D_frame/applyPenaltyOperatorITF.cu', ...
	'3D_frame/applyPenaltyOperator.cu', ...
	'3D_frame/assembleFemVectorITF.cu', ...
	'3D_frame/assembleFemVector.cu', ...
	'3D_frame/varifoldITF.cu', ...
	'3D_frame/varifold.cu', ...
	'3D_frame/dsum.cu', ...
	'3D_frame/vectoraxpby.cu', ...
	};
	
	fprintf('Compiling deformation (3D_frame)...\n');
	mexcuda(matlabFlag, '-DDIM3', ['-L', libDir], ['-I', includeDir], files, ...
	        '-lcublas', '-lcusolver', '-output', 'deformation_3D_frame');
	fprintf('\n');

end

